name: Third-Party Action Pinning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  third-party-action-pinning:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-third-party-action-pinning.yml
    with:
      source-repository: ${{ github.repository }}
      repository-ref: ${{ github.sha }}
